name: Release Please

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".vscode/**"
      - ".devcontainer/**"
      - ".gitignore"
      - ".pre-commit-config.yaml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
